name: OpenAPI Document Preparation
on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Get git diff
        id: git-diff
        run: echo "::set-output name=git-diff::$(echo $(git diff || echo true))"
      - name: Call OpenAPI Service
        env:
          REPO_VARIABLE: ${{ secrets.token }}
        run: |
          curl -X POST https://link-test.blueyonder.com/openaiext/deployments/gpt-0301/chat/completions?api-version=2023-03-15-preview \
               -H 'Content-Type: application/json' \
               -H "Authorization: Bearer $REPO_VARIABLE" \
               -d '{"messages":[{"role":"user","content":"I want a prepare a test case document. I want to analyze this code change $DIFF And return me a table with test-case id, test description and expected result in a tabular format"}]}'
